version: "3"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
  service1:
    image: jaxgeller/lwan
    volumes:
      - ./data:/lwan/wwwroot
  service2:
    image: jaxgeller/lwan
    volumes:
      - ./data:/lwan/wwwroot
  service3:
    image: jaxgeller/lwan
    volumes:
      - ./data:/lwan/wwwroot
  diffy:
    image: diffy/diffy
    ports:
      - "8880:8880"
      - "8881:8881"
      - "8888:8888"
    command:
      - "-candidate=service3:8080"
      - "-master.primary=service1:8080"
      - "-master.secondary=service2:8080"
      - "-service.protocol=http"
      - "-serviceName=Test-Service"
      - "-proxy.port=:8880"
      - "-admin.port=:8881"
      - "-http.port=:8888"
      - "-rootUrl=localhost:8888"
      - "-summary.email=''"
  krakend_ce:
    image: devopsfaith/krakend:1.4.1
    volumes:
      - ./krakend:/etc/krakend
    command:
      - "run"
      - "-d"
      - "-c"
      - "/etc/krakend/krakend.json"
    ports:
      - "8080:8080"
